export const CNFT = [
    {
        id: 0,
        name: "Cardano Crocs Club",
        title: "Meet the Crocs",
        image: "images/Croc1.png",
        alt: "Cardano Crocs Club Image",
        image2: "images/CardanoCrocsClub.png",
        description: "Project backed by CCC",
        popularity: 70,
        floorPrice: 270,
        rating: 5,
    },
    {
        id: 1,
        name: "CryptoDino",
        title: "Meet the Dinos",
        image: "images/CryptoDino.webp",
        alt: "Crypto Dino Image",
        description: "Prehistoric Cuties",
        floorPrice: 93,
        rating: 4,
    },
    {
        id: 2,
        name: "Grandmaster Adventurers",
        title: "Meet the Heroes",
        image: "images/GrandmasterAdventurer.gif",
        alt: "Grandmaster Adventurer Image",
        description: "Fantasy World Adventurers for a MMORPG Inn-management and questing game",
        floorPrice: 64,
        rating: 5,
    },
    {
        id: 3,
        name: "Pavia",
        title: "Discover the Metaverse",
        image: "images/Pavia.webp",
        alt: "Pavia Image",
        description: "The first metaverse land grab in the Cardano Ecosystem",
        floorPrice: 329,
        rating: 5,
    },
    {
        id: 4,
        name: "World of Cardano",
        title: "Mystical Metaverse",
        image: "images/worldOfCardanoForrest.png",
        alt: "World of Cardano Image",
        description: "A neo-medieval Metaverse project that offers the opportunity to exclusively acquire pieces of land in form of unique Cardano NFT (CNFT), based on specific coordinates. ",
        floorPrice: 60,
        rating: 4,
    },
    {
        id: 5,
        name: "Radioactive Crocs Club",
        title: "The Swamp Grows",
        image: "images/radioactiveCroc.png",
        alt: "Radioactive Crocs Image",
        description: "Cardano Crocs Club's second mint is fully metaverse-ready, and offers staking rewards that payout in C4 token",
        floorPrice: 71,
        rating: 5,
    },
    {
        id: 6,
        name: "Clay Mates",
        title: "Clay Nation",
        image: "images/clayNation.png",
        alt: "Clay Mates Image",
        description: "With many collections to choose from, and a history of big-name celebrity backers, Clay Nation is one of the biggest names in the CNFT space.",
        floorPrice: 2699,
        rating: 5,
    },
    {
        id: 7,
        name: "Boss Cat Rocket Club",
        title: "Meet the Boss",
        image: "images/bossCat.png",
        alt: "Boss Cat Rocket Club Image",
        description: "These space-bound cats are founded by one of the most intrepid teams of artists, game devs, and community managers.",
        floorPrice: 1799,
        rating: 5,
    },
    {
        id: 8,
        name: "Spacebudz",
        title: "Budz are out there",
        image: "images/spaceBudz.png",
        alt: "Spacebudz Image",
        description: "These suited-up space animals are some of the first on the chain, and the current biggest blue-chip NFT in the space.",
        floorPrice: 6400,
        rating: 5,
    },
    
]
