export const CNFT = [
    {
        id: 0,
        name: "Cardano Crocs Club",
        title: "Meet the Crocs",
        image: "images/Croc1.png",
        alt: "Cardano Crocs Club Image",
        image2: "images/CardanoCrocsClub.png",
        description: "Project backed by CCC",
        popularity: 70,
        floorPrice: 270,
        rating: 5,
    },
    {
        id: 1,
        name: "CryptoDino",
        title: "Meet the Dinos",
        image: "images/CryptoDino.webp",
        alt: "Crypto Dino Image",
        description: "Prehistoric Cuties",
        floorPrice: 93,
        rating: 5,
    },
    {
        id: 2,
        name: "Grandmaster Adventurers",
        title: "Meet the Heroes",
        image: "images/GrandmasterAdventurer.gif",
        alt: "Grandmaster Adventurer Image",
        description: "Fantasy World Adventurers for a MMORPG Inn-management and questing game",
        floorPrice: 64,
        rating: 5,
    },
    {
        id: 3,
        name: "Pavia",
        title: "Discover the Metaverse",
        image: "images/Pavia.webp",
        alt: "Pavia Image",
        description: "The first metaverse land grab in the Cardano Ecosystem",
        floorPrice: 329,
        rating: 5,
    },
    {
        id: 4,
        name: "World of Cardano",
        title: "Mystical Metaverse",
        image: "images/worldOfCardanoForrest.png",
        alt: "World of Cardano Image",
        description: "A neo-medieval Metaverse project that offers the opportunity to exclusively acquire pieces of land in form of unique Cardano NFT (CNFT), based on specific coordinates. ",
        floorPrice: 60,
        rating: 5,
    },
    
]
