export const CNFT = [
    {
        id: 0,
        name: "Cardano Crocs Club",
        title: "Meet the Crocs",
        image: "images/Croc1.png",
        image2: "images/CardanoCrocsClub.png",
        description: "Project backed by CCC",
        floorPrice: 270,
        rating: 5,
    },
    {
        id: 1,
        name: "CryptoDino",
        title: "Meet the Dinos",
        image: "images/CryptoDino.webp",
        description: "Prehistoric Cuties",
        floorPrice: 90,
        rating: 5,
    },
    {
        id: 2,
        name: "Grandmaster Adventurers",
        title: "Meet the Heroes",
        image: "images/GrandmasterAdventurer.gif",
        description: "Fantasy World Adventurers for a MMORPG Inn-management and questing game",
        floorPrice: 95,
        rating: 5,
    },
    {
        id: 3,
        name: "Pavia",
        title: "Discover the Metaverse",
        image: "images/Pavia.webp",
        description: "The first metaverse land grab in the Cardano Ecosystem",
        floorPrice: 350,
        rating: 5,
    },
]